baupen/web

src/DataFixtures/LoadMapData.php, src/DataFixtures/Resources/maps.json
not sure if the generation infrastructure can handle this yet, but it'd be very handy for testing the app
=> added map without file

.editorconfig, DEVELOPERS.MD, assets/js/app.js, assets/js/apps/Switch/bootstrap.js, assets/js/apps/Switch/components/ConstructionSite.vue, assets/js/apps/Switch/switch.vue, assets/js/localization/switch.js, assets/sass/elements/switch.sass, composer.lock, package.json, src/Api/Entity/Edit/Map.php, src/Api/Entity/Switch_/ConstructionSite.php, src/Api/Response/Data/ConstructionSitesData.php, src/Api/Transformer/Edit/MapFileTransformer.php, src/Api/Transformer/Edit/MapTransformer.php, src/Api/Transformer/Switch_/ConstructionSiteTransformer.php, src/Controller/Api/EditController.php, src/Controller/Api/SwitchController.php, src/Controller/SwitchController.php, src/DataFixtures/EnrichConstructionSiteData.php, src/DataFixtures/LoadIssueData.php, src/DataFixtures/Resources/construction_sites.json, src/Service/FileSystemSyncService.php, templates/switch/switch.html.twig, tests/Controller/Api/SwitchControllerTest.php, yarn.lock
=> add switch / subscribe to contruction view

DEVELOPERS.MD, composer.lock, config/packages/test/framework.yaml, config/services_test.yaml, src/Controller/Api/External/ConfigController.php, src/Controller/Api/FoyerController.php, src/Controller/Api/RegisterController.php, src/DataFixtures/EnrichConstructionSiteData.php, src/Model/SyncTransaction.php, src/Service/Sync/DisplayNameService.php, src/Service/Sync/FileService.php, src/Service/Sync/MapSectorService.php, src/Service/Sync/MapService.php, src/Service/SyncService.php, tests/Controller/Api/DispatchControllerTest.php, tests/Controller/Api/External/ConfigControllerTest.php
Implements domain config node.
=> resolves #119

assets/js/apps/Dashboard/components/Feed.vue, assets/js/apps/Dashboard/components/Notes.vue, assets/js/apps/Switch/components/ConstructionSite.vue, assets/js/apps/Switch/switch.vue, assets/js/font_awesome_light.js, assets/js/localization/dashboard.js, assets/js/localization/switch.js, assets/sass/app.sass, assets/sass/elements/modal.sass, src/Controller/Api/RegisterController.php, src/Controller/Api/SwitchController.php, src/Controller/External/Report/FilterController.php, src/Controller/SwitchController.php, src/Controller/Traits/QueryParseTrait.php, src/Entity/ConstructionManager.php, src/Entity/ConstructionSite.php, src/Migrations/Version20190317100207.php, src/Service/Interfaces/ReportServiceInterface.php, src/Service/Interfaces/SyncServiceInterface.php, src/Service/Report/IssueReport/NewReportService.php, src/Service/ReportService.php, src/Service/SyncService.php, src/Service/TrialService.php, templates/admin_layout.html.twig, templates/help/overview.html.twig, templates/help/overview_content.html.twig, translations/help.de.yml, translations/report.de.yml, translations/report.it.yml, translations/switch.de.yml
=> resolves #148

assets/js/apps/Dashboard/components/Feed.vue, assets/js/apps/Dashboard/components/Notes.vue, assets/js/apps/Switch/components/ConstructionSite.vue, assets/js/apps/Switch/switch.vue, assets/js/font_awesome_light.js, assets/js/localization/dashboard.js, assets/js/localization/switch.js, assets/sass/app.sass, assets/sass/elements/modal.sass, src/Controller/Api/RegisterController.php, src/Controller/Api/SwitchController.php, src/Controller/External/Report/FilterController.php, src/Controller/SwitchController.php, src/Controller/Traits/QueryParseTrait.php, src/Entity/ConstructionManager.php, src/Entity/ConstructionSite.php, src/Migrations/Version20190317100207.php, src/Service/Interfaces/ReportServiceInterface.php, src/Service/Interfaces/SyncServiceInterface.php, src/Service/Report/IssueReport/NewReportService.php, src/Service/ReportService.php, src/Service/SyncService.php, src/Service/TrialService.php, templates/admin_layout.html.twig, templates/help/overview.html.twig, templates/help/overview_content.html.twig, translations/help.de.yml, translations/report.de.yml, translations/report.it.yml, translations/switch.de.yml
=> Add construction site for #123

assets/js/apps/Switch/bootstrap.js, assets/js/apps/Switch/components/AddConstructionSiteForm.vue, assets/js/apps/Switch/components/ConstructionSite.vue, assets/js/apps/Switch/switch.vue, assets/js/localization/shared/_all.js, assets/js/localization/shared/validation.js, assets/js/localization/switch.js, package.json, src/Api/Entity/Switch_/ConstructionSite.php, src/Api/Request/_Switch/CreateCheckRequest.php, src/Api/Request/_Switch/CreateRequest.php, src/Api/Response/Data/_Switch/CheckData.php, src/Api/Transformer/Switch_/ConstructionSiteTransformer.php, src/Controller/Api/SwitchController.php, src/Controller/Base/BaseController.php, templates/admin_layout.html.twig, tests/Controller/Api/SwitchControllerTest.php, yarn.lock
=> Add construction site create

src/Controller/Api/EditController.php
Ensure the parents are marked as changed when the child parentId changes to resolve #262
=> resolve #262

src/Controller/DashboardController.php, src/Service/Report/Legacy/Report.php, src/Service/ReportService.php
fixes small issues when rendering PDFs.
=> Improve PDF rendering

config/services.yaml, src/Api/DataProvider/IssueReportDataProvider.php, src/Api/DataProvider/SerializerAwareDataProvider.php, src/Service/Interfaces/ReportServiceInterface.php, src/Service/Report/Report.php, src/Service/ReportService.php
=> Scalability

assets/css/app.scss, assets/css/bootstrap-responsive.scss, assets/js/vue/components/ResolveIssues.vue, assets/js/vue/components/View/IssueResolveCard.vue, assets/js/vue/components/View/MapIssuesResolveView.vue, assets/js/vue/components/View/MapsResolveTable.vue, assets/js/vue/localization/de.json, templates/public/_public_layout.html.twig
=> Improve resolve

assets/js/app.js, assets/js/vue/components/Action/AssociateConstructionManagerButton.vue, assets/js/vue/components/DashboardFeed.vue, assets/js/vue/components/Form/CraftsmanForm.vue, assets/js/vue/components/Form/FileForm.vue, assets/js/vue/components/Form/ImageForm.vue, assets/js/vue/components/SwitchConstructionSites.vue, assets/js/vue/components/View/CraftsmenEditTable.vue, assets/js/vue/components/View/CraftsmenStatisticsTable.vue, assets/js/vue/components/View/IssuesTable.vue, assets/js/vue/components/View/MapsEditTable.vue, assets/js/vue/localization/de.json, migrations/Version20210222083810.php, src/DataFixtures/ConstructionSiteFixtures.php, src/Extension/MyTwigExtension.php, src/Security/Voter/ConstructionManagerVoter.php, translations/email.de.yml
=> First time flow

assets/css/app.scss, config/packages/doctrine.yaml, src/Api/DataProvider/CraftsmanStatisticsDataProvider.php, src/Command/MigrateSqliteCommand.php, src/Doctrine/UTCDateTimeType.php, tests/Traits/Api/AssertApiCollectionFilterTrait.php
The datetime comparison is off by an hour (due to localtime being +1).
=> Fixes datetime comparison

config/packages/api_platform.yaml, src/Api/OpenApi/OpenApiFactory.php, src/Controller/ApiController.php, src/Doctrine/UTCDateTimeType.php, src/Helper/DateTimeFormatter.php, tests/Api/ApiControllerTest.php, tests/Traits/Api/AssertApiCollectionFilterTrait.php, tests/Traits/Api/AssertApiPostTrait.php, tests/Traits/AuthenticationTrait.php
=> Add delete images

assets/css/app.scss, assets/js/vue/Dashboard.vue, assets/js/vue/components/DashboardIssuesGraph.vue, assets/js/vue/components/DashboardIssuesSummary.vue, assets/js/vue/services/api.js, config/services.yaml, package.json, src/Api/DataProvider/IssueTimeseriesDataProvider.php, src/Api/Entity/IssueSummaryWithDate.php, src/Api/Filters/PatchedOrderFilter.php, src/Entity/Issue.php, tests/Api/IssueTest.php, yarn.lock
=> Enhancements

assets/js/vue/Dashboard.vue, assets/js/vue/components/Action/ExportIssuesButton.vue, assets/js/vue/components/Action/GenerateIssuesReport.vue, assets/js/vue/components/DashboardConstructionSite.vue, assets/js/vue/components/DashboardFeed.vue, assets/js/vue/components/DashboardIssuesGraph.vue, assets/js/vue/components/Form/IssueFilter/MapFilter.vue, assets/js/vue/components/ResolveIssues.vue, assets/js/vue/components/View/FeedEntry.vue, assets/js/vue/components/View/IssueResolveCard.vue, assets/js/vue/components/View/MapsResolveTable.vue, assets/js/vue/localization/de.json, src/Repository/IssueRepository.php
=> Enhancements & bugfixes

.travis.yml, assets/js/vue/components/DashboardIssuesGraph.vue, src/Api/DataProvider/IssueReportDataProvider.php, src/Api/DataProvider/IssueTimeseriesDataProvider.php, src/Api/DataProvider/SerializerAwareDataProvider.php, src/Api/OpenApi/OpenApiFactory.php, src/Command/Base/DatabaseCommand.php, src/Command/DatabaseBackupCommand.php, src/Command/DatabaseRestoreCommand.php, src/Command/MigrateSqliteCommand.php, src/Controller/ApiController.php, src/Controller/SecurityController.php, src/DataFixtures/ConstructionSiteFixtures.php, src/DataFixtures/Model/AssetFile.php, src/Doctrine/Driver.php, src/Doctrine/UTCDateTimeType.php, src/Entity/ConstructionManager.php, src/Repository/IssueRepository.php, src/Security/TokenAuthenticator.php, src/Security/Voter/IssueVoter.php, src/Service/Image/GdService.php, src/Service/ImageService.php, src/Service/MapFileService.php, src/Service/Report/ReportElements.php, src/Service/StorageService.php, tests/Api/CraftsmanTest.php, tests/Api/IssueTest.php
=> Reduce technical dept

assets/js/app.js, assets/js/vue/components/Action/EditIssuesButton.vue, assets/js/vue/components/Action/ViewIssueButton.vue, assets/js/vue/components/Form/IssuesForm.vue, assets/js/vue/components/View/IssueRenderLightbox.vue, assets/js/vue/components/View/IssueResolveCard.vue, assets/js/vue/components/View/IssuesTable.vue, config/packages/security.yaml, src/Api/DataProvider/IssueRenderDataProvider.php, src/Api/Serializer/IssueSerializer.php, src/Controller/ApiController.php, src/Entity/Issue/IssuePositionTrait.php, src/Service/Image/GdService.php, src/Service/ImageService.php, src/Service/Interfaces/ImageServiceInterface.php, tests/Api/IssueTest.php
Add render crosshair & other small improvements
=> Add render crosshair

assets/js/vue/components/Action/EditIssuesButton.vue, assets/js/vue/components/Form/IssuesForm.vue, assets/js/vue/components/View/IssuesTable.vue
=> Hide state change from UI

src/Service/Image/GdService.php, src/Service/Image/GsService.php, src/Service/ImageService.php
=> Improve image rendering

src/Service/Report/Pdf/Report.php
Resolves bug that footer is not always added
=> fix: Ensure footer always added
